petcollector/pet_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('about/', views.about, name='about'),
    path('collection/', views.pet_index, name='pet-index'),
    path('collection/<int:pet_id>/', views.pet_detail, name='pet-detail'),
    path('collection/create/', views.PetCreate.as_view(), name='pet-create'),
    path('collection/<int:pk>/update/', views.PetUpdate.as_view(), name='pet-update'),
    path('collection/<int:pk>/delete/', views.PetDelete.as_view(), name='pet-delete'),
    path('collection/<int:pet_id>/add-playdate/', views.add_playdate, name='add-playdate'),
    path('collection/<int:pet_id>/playdate/<int:pk>/update/', views.PlaydateUpdate.as_view(), name='playdate-update'),
    path('collection/<int:pet_id>/playdate/<int:pk>/delete/', views.PlaydateDelete.as_view(), name='playdate-delete'),
    path('accounts/signup/', views.signup, name='signup')
]

petcollector/petcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pet_app.urls')),
    #path('about/', include('pet_app.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

petcollector/pet_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


FRIENDS = (
    ('Dug', 'Dug'),
    ('Roz', 'Roz'),
    ('Grandpa', 'Grandpa'),
    ('Spooky', 'Spooky'),
    ('Fig', 'Fig')
)

class Pet(models.Model):
    name = models.CharField(max_length=100)
    type = models.CharField(max_length=100)
    breed = models.CharField(max_length=500)
    fun_fact = models.CharField(max_length=100)
    age = models.IntegerField()
    image = models.ImageField(upload_to='pet_images/', blank=True, null=True)

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('pet-detail', kwargs={'pet_id': self.id})

class Playdate(models.Model):
    date = models.DateField('Playdate Date')
    friend = models.CharField(
        max_length=100,
        choices=FRIENDS,
        default=FRIENDS[0])
    
    pet = models.ForeignKey(Pet, on_delete=models.CASCADE)
    
    def __str__(self):
        return f'{self.get_friend_display()} on {self.date}'
    
    def get_absolute_url(self):
        print('error', self.id)
        return reverse('pet-detail', kwargs={'pet_id': self.pet_id})
    
    class Meta:
        ordering = ['-date']

petcollector/pet_app/forms.py
from django import forms
from .models import Playdate

class PlaydateForm(forms.ModelForm):
    class Meta:
        model = Playdate
        fields = ['date', 'friend']
        widgets = {
            'date': forms.DateInput(
                format=('%Y-%m-%d'),
                attrs={
                    'placeholder': 'Select a date',
                    'type': 'date'
                }
            ),
        }

petcollector/pet_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Pet, Playdate
from .forms import PlaydateForm
from django.urls import reverse
from django.contrib.auth.views import LoginView
from django.views.generic import ListView, DetailView
# Add the two imports below
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin



class Home(LoginView):
    template_name= 'home.html'

def about(request):
    return render(request, 'about.html')

@login_required
def pet_index(request):
    pets = Pet.objects.filter(user=request.user)
    return render(request, 'collection/index.html', {'pets': pets})

@login_required
def pet_detail(request, pet_id):
    pet = Pet.objects.get(id=pet_id)
    playdate_form = PlaydateForm()
    return render(request, 'collection/detail.html', {
        'pet': pet,
        'playdate_form': playdate_form
    })

class PetCreate(LoginRequiredMixin, CreateView):
    model = Pet
    fields = '__all__'
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class PetUpdate(UpdateView):
    model = Pet
    fields = ['type', 'breed', 'fun_fact', 'age']

class PetDelete(DeleteView):
    model = Pet
    success_url = '/collection/'

@login_required
def add_playdate(request, pet_id):
    form = PlaydateForm(request.POST)
    if form.is_valid():
        new_playdate = form.save(commit=False)
        new_playdate.pet_id = pet_id
        new_playdate.save()
    return redirect('pet-detail', pet_id=pet_id)

class PlaydateUpdate(UpdateView):
    model = Playdate
    fields = ['date', 'friend']
    #success_url = '/collection/'
    # def form_valid(self, form):
    #     #form = PlaydateForm(request.PUT)
    #     if form.is_valid():
    #         edit_playdate = form.save(commit=False)
    #         edit_playdate.pet_id = pet_id
    #         edit_playdate.save()
    #     return redirect('pet-detail', pet_id=pet_id)

class PlaydateDelete(DeleteView):
    model = Playdate
    def get_success_url(self):
        return reverse('pet-detail', kwargs={'pet_id': self.object.pet.id})

def signup(request):
    error_message = ''
    if request.method == 'POST':
        # This is how to create a 'user' form object
        # that includes the data from the browser
        form = UserCreationForm(request.POST)
        if form.is_valid():
            # This will add the user to the database
            user = form.save()
            # This is how we log a user in
            login(request, user)
            return redirect('pet-index')
        else:
            error_message = 'Invalid sign up - try again'
    # A bad POST or a GET request, so render signup.html with an empty form
    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'signup.html', context)
    # Same as: 
    # return render(
    #     request, 
    #     'signup.html',
    #     {'form': form, 'error_message': error_message}
    # )

petcollector/pet_app/templates/about.html
{% extends 'base.html' %}
{% block content %}
  <h1>About the Pet Collector</h1>
  <hr />
  <p class="page-content">
    I have had animals since I was five years old. Growing up we hand raised
    parakeets, with an aviary with up to 40 parakeets. We had turtles, fish,
    tortoises, snakes, rats, hamsters, dogs, fish, lizards. If you can name it, I've
    most likely had it!
  </p>

  <p class="page-content">
    I love animals; they are a part of my everyday life. As an adult, I have
    the privilege of being called "The Dog Father" with three dogs and two
    cats. Plans to expand the fur family include a tortoise and chickens as of
    October 2025. But knowing my wife and I, that probably will not be enough!
  </p>
  <img src="{% static 'images/christmas.jpeg' alt='Christmas Puppies'}" />
{% endblock %}

petcollector/pet_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" type="image/png" href="" />
    <link rel="stylesheet" href="{% static 'css/base.css' %}"/>
    <title>Pet Collector</title>
    {% block head %}{% endblock %}
  </head>

  <body>
    <header>
      <div class="header-logo-container">
        <a href="/">
          <img src="" alt="The Pet Collector Logo" />
        </a>
      </div>
      <nav>
        <ul>
          {% if user.is_authenticated %}
            <li><a href="{% url 'pet-index' %}">Collection</a></li>
            <li><a href="{% url 'pet-create' %}">Add a Pet</a></li>
            <li><a href="{% url 'about' %}">About</a></li>
            <li>
              <form id="logout-form" method="post" action="{% url 'logout' %}">
                {% csrf_token %}
                <button type="submit">Log out</button>
              </form>
            </li>
          {% else %}
            <li><a href="{% url 'about' %}">About</a></li>
            <li><a href="{% url 'home' %}">Login</a></li>
            <li><a href="{% url 'signup' %}">Sign Up</a></li>
          {% endif %}
        </ul>
      </nav>
    </header>

    <main>
      {% block content %}
      {% endblock %}
    </main>
  </body>
</html>

petcollector/pet_app/templates/collection/detail.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/collection/pet-detail.css' %}">
{% endblock %}

{% block content %}
<section class="pet-container">
    <div class="pet-img">
        {% if pet.image %}
        <img src="{{ pet.image.url }}" alt="{{ pet.name }}">
        {% else %}
        <img src="{% static 'images/default-pet.svg' %}" alt="{{ pet.name }}">
        {% endif %}
    </div>

    <div class="pet-details">
        <h1>{{ pet.name }}</h1>
        {% if pet.age > 0 %}
        <h2>A {{ pet.age }} year old {{ pet.breed }}</h2>
        {% else %}
        <h2>A {{ pet.breed }} kitten.</h2>
        {% endif %}
        <p>{{ pet.fun_fact }}</p>

        <div class="pet-actions">
            <a href="{% url 'pet-update' pet.id %}" class="btn warn">Edit</a>
            <a href="{% url 'pet-delete' pet.id %}" class="btn danger">Delete</a>
        </div>
    </div>
</section>

<div class="playdate-container">
    <section class="playdates">
        <div class="subsection-title">
            <h2>Playdates</h2>
        </div>
        <h3>Schedule a Playdate</h3>
        <form action="{% url 'add-playdate' pet.id %}" method="post" class="subsection-content" autocomplete="off">
            {% csrf_token %}
            {{ playdate_form.as_p }}
            <button type="submit" class="btn submit">Schedule Playdate</button>
        </form>
        <div class="playdate-cards">
            {% for playdate in pet.playdate_set.all %}
            <div class="playdate-card">
                <p><strong>Date:</strong> {{ playdate.date }}</p>
                <p><strong>With:</strong> {{ playdate.get_friend_display }}</p>
                <div class="playdate-actions">
                    <a href="{% url 'playdate-update' pet.id playdate.id %}" class="btn warn">Edit</a>
                    <a href="{% url 'playdate-delete' pet.id playdate.id %}" class="btn danger">Delete</a>
                </div>
            </div>
            {% empty %}
            <p>No playdates scheduled.</p>
            {% endfor %}
        </div>
    </section>
</div>
{% endblock %}

petcollector/pet_app/templates/collection/index.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/collection/pet-index.css' %}">
{% endblock %}

{% block content %}
<section class="page-header">
  <h1>The Pet Collection</h1>
</section>

<section class="card-container">
  {% for pet in pets %}
    <div class="card">
      <a href="{% url 'pet-detail' pet.id %}">
        <div class="card-img-container">
          {% if pet.image %}
            <img src="{{ pet.image.url }}" alt="{{ pet.name }}">
          {% else %}
            <img src="{% static 'images/default-pet.svg' %}" alt="{{ pet.name }}">
          {% endif %}
        </div>

        <div class="card-content">
          <h2 class="card-title">{{ pet.name }}</h2>

          {% if pet.age > 0 %}
            <p>A {{ pet.age }} year old {{ pet.breed }}</p>
          {% else %}
            <p>A {{ pet.breed }} kitten.</p>
          {% endif %}

          <p><small>{{ pet.fun_fact }}</small></p>
        </div>
      </a>
    </div>
  {% endfor %}
</section>
{% endblock %}

petcollector/pet_app/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/base.css' %}">
{% endblock %}

{% block content %}
<section>
    {% if not user.is_authenticated %}
    <form method="post" action="{% url 'home' %}" class="login">
        <h1>Login</h1>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="hidden" name="next" value="{{ next }}" />
        <button type="submit" class="btn submit">Login</button>
    </form>
    {% else %}
    <p>Welcome, {{ user.username }}!</p>
    {% endif %}
</section>
{% endblock %}

petcollector/pet_app/templates/pet_app/pet_confirm_delete.html
{% extends 'base.html' %}  
{% load static %} 
{% block content %}

<div class="page-header">
  <h1>Delete Pet?</h1>
</div>

<h2>Are you sure you want to delete {{ pet.name }}?</h2>

<form action="" method="post" class="form">
  {% csrf_token %}
  <a href="{% url 'pet-detail' object.id %}" class="btn secondary">Cancel</a>
  <button type="submit" class="btn danger">Yes - Delete!</button>
</form>

{% endblock %}

petcollector/pet_app/templates/pet_app/pet_form.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/form.css' %}" />
{% endblock %}
{% block content %}

<div class="page-header">
    {% if pet %}
        <h1>Edit {{ pet.name }}</h1>
    {% else %}
        <h1> Add a Pet </h1>
    {% endif %}
</div>

<form action="" method="post" class="'form-container">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <button type="submit" class="btn submit">Submit!</button>
</form>

{% endblock %}

petcollector/pet_app/templates/pet_app/playdate_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
  <h1>Delete Playdate</h1>
  <p>Are you sure you want to delete this playdate?</p>
  <form method="post" action="" class="form">
    {% csrf_token %}
    <a href="{% url 'pet-detail' object.id %}" class="btn warn">Cancel</a>
    <button type="submit" class="btn danger">Yes, delete</button>
  </form>
{% endblock %}

petcollector/pet_app/templates/pet_app/playdate_form.html
{% extends 'base.html' %}
{% block content %}
  <h1>Edit Playdate</h1>
  <form method="post" action="" class="form-container">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn submit">Save Changes</button>
  </form>
{% endblock %}

petcollector/pet_app/templates/signup.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/form.css' %}" />
{% endblock %} 
{% block content %}
<div class="page-header">
  <h1>Sign Up</h1>
  <img src="{% static 'images/nerd-cat.svg' %}" alt="A cat using a computer" />
</div>
{% if error_message %}
  <p class="red-text">{{ error_message }}</p>
{% endif %}
<form action="" method="post" class="form-container" autocomplete="off">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <button type="submit" class="btn submit">Submit!</button>
</form>

{% endblock %}